### ISSUE TITLE
Error on enum type with dot symbol or numeric value

### ISSUE THREAD

**Issue by mikenavi** [mancku/strapi-plugin-schemas-to-ts#14]
If Strapi enum field value contains dot inside the string, the plugin generate ts enum type with dot which doesn't match the ts-syntax

```json
"ghostPriceRounding": {
      "type": "enumeration",
      "enum": ["X.00", "X.99", "X.95"]
    }
```

```ts
export enum GhostPriceRounding {
  X.00 = 'X.00',
  X.99 = 'X.99',
  X.95 = 'X.95',}
```

**Comment by mikenavi** [comment]
The same thing with enum string values which contains only digits:

```json
"year": {
      "type": "enumeration",
      "required": true,
      "enum": [
        "2012",
        "2013",
        "2014"
      ]
    }
```

creates not valid enum (cannot have a numeric name):

```ts
export enum Year {
  2012 = '2012',
  2013 = '2013',
  2014 = '2014',
  2015 = '2015',
  2016 = '2016',
  2017 = '2017',
  2018 = '2018',
  2019 = '2019',
  2020 = '2020',
  2021 = '2021',
  2022 = '2022',
  2023 = '2023',}
```

**Comment by mancku** [comment]
Hi @mikenavi thanks for reporting this. I'm not 100% happy with the solutions that are coming to my mind at first sight. Those would be:
- Adding the prefix `Option` to the values, so any value beginning with a number will now begin with a letter. I'd put that to all enum values, so the implementation is homogenic.
- I'd delete everything that's not a letter of a number for the value names. I'd even delete any letter with accents.
 
So these enums will be:
```ts
export enum Year {
  Option2012 = '2012',
  Option2013 = '2013',
  Option2014 = '2014',}
```

And 

```ts
export enum GhostPriceRounding {
  OptionX00 = 'X.00',
  OptionX99 = 'X.99',
  OptionX95 = 'X.95',}
```

**Comment by mancku** [comment]
Now @mikenavi I've done some tests and I see that (at least in Strapi 4.7.1) you can't create an enum value that begins with a number. If you do it in the admin panel, you can't save, and you'll see an error like this one:
![The text area where enum values are entered in the Strapi admin panel. I've entered the values 2012, 2013 and 2014. When I tried to save, the error said: "At least one value is invalid. Values should have at least one alphabetical character preceeding the first occurence of a number."](https://github.com/mancku/strapi-plugin-schemas-to-ts/assets/14790756/ba4325d4-5ac8-4298-bbc1-9d0e40dafd1a)

If you try to do it by manually modifying the schema.json file, the compilation will crash with this error:
> error: Content Type Definition is invalid for api::xxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxx'.
Invalid enumeration value. Values should have at least one alphabetical character preceeding the first occurence of a number. Update your enumeration 'yyyyyyyyy'.

So, I wouldn't add the Option prefix, then.
Also, instead of deleting any letter with accents, I'd just remove the accent from the letter.

**Comment by mikenavi** [comment]
Hello,

I check, and you right, it is not possible to declare numeric-only values with ui. Maybe it was possible earlier or this model was created without ui, but it work as is in one of product environments 😄 

And I think option prefix is a great. Thank you

**Comment by mikenavi** [comment]
UPD. In the current situation, when it is impossible to set only a numeric value, I think it will be enough to simply sanitize the input: `X.00` -> `X00`

**Comment by mancku** [comment]
I agree @mikenavi. I think if a project is so old that it allows such values, it should be updated. Not for the sake of this plugin, but for security reasons maybe. So I'll move on with the sanitizing, but without the Option prefix. Then I'll explain that in the Readme

**Comment by mikenavi** [comment]
@mancku I make one more test, it is still possible to declare model manually with numbers as strings in enum field, in components. But this is definitely the strapi issue.

![image](https://github.com/mancku/strapi-plugin-schemas-to-ts/assets/4928270/9b8f5fa2-4efd-475a-9017-35b2fbb0eed0)

**Comment by mancku** [comment]
@mikenavi you did a great work finding that one! I agree it's an issue in the Strapi side. Did you reported it?
Anyway, regarding the plugin behavior, what I'm gonna do is to add an underscore `_` as a suffix of the properties that begin with a number. I think that's way cleaner than to add the word `Option` as a suffix to all enum values.

**Comment by mikenavi** [comment]
> Did you reported it?
no, but i'm going to

> I'm gonna do is to add an underscore
I am very appreciate, but think it is not necessary, because the main issue based on buggy logic of the core. Your plugin is awesome, and, imho, there is no reason to waste your valuable time to support that behaviour.

And again, thank you very much, plugin is really awesome

**Comment by mancku** [comment]
Hi @mikenavi! first of all thank you for your kind words. I'm happy that this plugin is of help to you 😊

In a couple hours I'll be uploading the new version and I finally decided to leave the underscore, because even if it's a bug from Strapi (which I agree, it looks like) it can happen to other devs to be stuck in a version where they have to deal with that, and at the end is really a very little effort.
