### ISSUE TITLE
Name conflict with enum field

### ISSUE THREAD

**Issue by mikenavi** [mancku/strapi-plugin-schemas-to-ts#15]
If field and scheme share the same name (in enum field) it creates ts name conflict

```json
{
  "attributes": {
    "rating": {
      "type": "enumeration",
      "required": true,
      "enum": ["a", "b"]
    },
    "years": {
      "type": "component",
      "repeatable": true,
      "component": "organization-elements.rating-year"
    }
  }
}
```

```ts
export enum Rating {
  a = "a",
  b = "b",
}

export interface Rating {
  rating: Rating;
  years: RatingYear[];
}

```

the same name `Rating` is given to interface and enum

**Comment by mancku** [comment]
Hi @mikenavi 

The answer here would be very similar to the one I've given you in https://github.com/mancku/strapi-plugin-schemas-to-ts/issues/14#issuecomment-1635748922

I'd add the suffix Enum to the names, so you'd end up having:
```ts
export enum RatingEnum {
  a = "a",
  b = "b",
}

export interface RatingEnum {
  rating: Rating;
  years: RatingYear[];
}
```

I did originally discard that option because it seemed redundant, but didn't foresee the problem you're pointing out here.
As I said in that other comment, I'd be happy to hear your opinion or ideas and try to have it fixed during the weekend.

**Comment by mancku** [comment]
You're right @mikenavi. It's a copy-paste mistake. It'll look exactly as in your example

**Comment by mancku** [comment]
Hi @mikenavi I wanted let you know that In a couple hours I'll upload a new version, and that I added a new property to the configuration to add the "Enum" suffix to all enums (default false) so if that's set to true, all enums generated by the plugin will have it. Otherwise only the ones that their name collides with any of the generated class names, will get the preffix
