### ISSUE TITLE
Self-dependency not handled well in the case of _Plain interfaces

### ISSUE THREAD

**Issue by kovacsgergelydpr** [mancku/strapi-plugin-schemas-to-ts#16]
When using Relations in Strapi, which points to the same collection type, where they are placed, the Plugin generates improper code: tries to import _Plain interfaces from itself.

While self dependencies avoided correctly in the case of 'normal' interfaces (named without _Plain postfix), the _Plain interfaces generates imports, that points to the same file, where they are.

For example:

device-category.ts
```
import { DeviceCategory_Plain } from './device-category'; // <----- Error!

export interface DeviceCategory {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    device_categories: { data: DeviceCategory[] };
  };
}
export interface DeviceCategory_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  device_categories: DeviceCategory_Plain[];
}
```
Thanks!

**Comment by mancku** [comment]
Hi @kovacsgergelydpr that should've fixed in 1.1.1. I tested it with an example of my own and it adds the _Plain reference without the Import. 

Please, could you add more context?
- Version of Strapi
- Version of the strapi-plugin-schema-to-ts
- The schema.js version used to generate device-category.ts

Here's my whole file content as a reference.
```ts
// Interface automatically generated by schemas-to-ts
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Catalog {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    Name?: string;
    numOfItems?: number;
    catalog?: { data: Catalog };
    catalogs: { data: Catalog[] };
  };
}
export interface Catalog_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Name?: string;
  numOfItems?: number;
  catalog?: Catalog_Plain;
  catalogs: Catalog_Plain[];
}

export interface Catalog_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Name?: string;
  numOfItems?: number;
  address_of_very_important_person?: number;
  catalog?: number;
  catalogs: number[];
}

export interface Catalog_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Name?: string;
  numOfItems?: number;
  catalog?: AdminPanelRelationPropertyModification<Catalog_Plain>;
  catalogs: AdminPanelRelationPropertyModification<Catalog_Plain>[];
}

```

**Comment by matepaiva** [comment]
I am also having the same issue. Version 1.1.4.

**Comment by mancku** [comment]
@kovacsgergelydpr @matepaiva I fixed this and published the fix in the 1.1.5 version of the package in npm.
In my example in https://github.com/mancku/strapi-plugin-schemas-to-ts/issues/16#issuecomment-1637135284 I wasn't experiencing the error because catalog is single-worded, so the import path and the pascal name were the same. 

When a schema name is not single-worded in Strapi, it will have a hyphen between each pair of words, so the import path would be different from the pascal name.

**Comment by kovacsgergelydpr** [comment]
@mancku, Thanks, it works at first sight!

**Comment by matepaiva** [comment]
@mancku thank you! 👯‍♂️
